service: xpanxion-dev-essentials-services
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: us-east-1
  role: arn:aws:iam::797753794445:role/appServices

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - handler.js
  exclude:
    -  node_modules/**/*

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  addUser:
    handler: app/app.addUser
    events:
      - http:
          path: user
          method: post

# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userByEmail
            KeySchema:
              - AttributeName: Email
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                  - FullName
                  - PhoneNumber
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    UserScoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}Organizations
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: "N"
          - AttributeName: GiverId
            AttributeType: "N"
          - AttributeName: GetterId
            AttributeType: "N"
          - AttributeName: Score
            AttributeType: "N"
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2